---
# Site settings
title: Shengfan Shen
description: I am Shengfan Shen. I will soon be an incoming Master student at the School of Intelligence Science and Technology, Nanjing University, advised by Prof. Shuai Wang.
url: https://ssf-1103.github.io
avatar: /avatar.jpg
author:
  name: Shengfan Shen
  email: ssf031103@gmail.com
  github: SSF-1103

# Theme
remote_theme: vszhub/not-pure-poole

# Build settings
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

# Sass
sass:
  sass_dir: _sass
  style: :compressed

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: page
      title: About Me
---
